name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Account Service Docker image
      run: | 
        cd src/AccountService
        docker build -t account-service:latest .
        docker images
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag account-service:latest ${{ secrets.DOCKERHUB_USERNAME  }}/account-service:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME  }}/account-service:latest
