name: Conditional Deploy

on:
  push:
    branches: [ "jihao/garbage" ]
    paths:
      - 'src/AccountService/DonorService/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: ap-southeast-1
          aws-access-key: AKIAZLXYWSC5SOBYRJVK
          aws-secret-key: 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
          pipeline-name: donor
